FirstDjango/apps/articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:article_id>/', views.detail, name = 'detail'),
    path('<int:article_id>/put_comment/', views.put_comment, name = 'put_comment')
]

FirstDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('articles/', include('articles.urls')),
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
]

FirstDjango/apps/articles/models.py
import datetime
from django.db import models
from django.utils import timezone


class Article(models.Model):
    article_title = models.CharField('name of article', max_length=200)
    article_text = models.TextField('content of article')
    pub_date = models.DateTimeField('date of article publication')

    def __str__(self):
        return self.article_title

    def was_published_recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days=7))

    class Meta:
        verbose_name = 'article'
        verbose_name_plural = 'articles'


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField('name of author', max_length=50)
    comment_text = models.CharField('text of comment', max_length=200)

    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name = 'комментарий'
        verbose_name_plural = 'комментарии'

FirstDjango/apps/articles/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import Article

def index(request):
    last_articles_list = Article.objects.order_by('-pub_date')[:5]
    return render(request, 'articles/list.html', {'last_articles_list': last_articles_list})

def detail(request, article_id):
    try:
        a = Article.objects.get( id = article_id )
    except:
        raise Http404("Article is not found")
    last_comments_list = a.comment_set.order_by('-id')[:10]
    return render(request, 'articles/detail.html', {'article': a, 'last_comments_list': last_comments_list})

def put_comment(request, article_id):
    try:
        a = Article.objects.get( id = article_id )
    except:
        raise Http404("Article is not found")
    a.comment_set.create(author_name = request.POST['name'], comment_text = request.POST['text'])
    return HttpResponseRedirect(reverse('articles:detail', args=(a.id,)))

FirstDjango/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %} {{article.article_title}} {% endblock %}

{% block content %}
<h2>{{article.article_title}}</h2>
<p>{{article.article_text}}</p>
<p><i>{{article.pub_date}}</i></p>

{% if article.was_published_recently %}
НОВАЯ СТАТЬЯ
{% endif %}

<hr>

{% if last_comments_list %}
    {% for c in last_comments_list %}
        <p>
            <strong>{{c.author_name}}</strong><br>
            <i>{{c.comment_text}}</i>
        </p>
    {% endfor %}
{% else %}
Comments are not found. Be the first!
{% endif %}

<hr>

<form action="{% url 'articles:put_comment' article.id %}" method="post">

    {% csrf_token %}

    <input type="text" required placeholder="Your name" name="name"><br>
    <textarea name="text" required placeholder="Text of Comment" cols="30" rows="10"></textarea><br>
    <button type="submit">PUT COMMENT</button>

</form>
{% endblock %}

FirstDjango/templates/articles/list.html
{% extends 'base.html' %}

{% block title %} Last Articles {% endblock %}

{% block content %}

    {% if last_articles_list %}

        {% for a in last_articles_list %}
            <a href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a><br>
        {% endfor %}

    {% else %}
        Articles are not found
    {% endif %}

{% endblock %}

FirstDjango/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My Site{% endblock %}</title>
</head>
<body>

    {% block content %}{% endblock %}

</body>
</html>